parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     atom-uploader-example
    database_user:     atom-uploader-example
    database_password: atom-uploader-example
    database_path: "%kernel.root_dir%/../src/Resources/data/orm.sqlite"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    # A secret key that's used to generate certain security-related tokens
    secret: 185f66f57220597efd21c8c1f0864f505dd673f7
