engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
    exclude_fingerprints:
      - 07c7560c53d94594ecb6eb907939edd5
      - c8e2165a03ccf4a385fadb110e871578
  fixme:
    enabled: true
  phpmd:
    enabled: true

ratings:
  paths:
    - "**.php"

exclude_paths:
  - features/
  - spec/
  - example-app/
  - devops/
  - src/DependencyInjection/
