language: php
sudo: false

php:
  - 5.6
  - 7.0

cache:
  directories:
    - "$HOME/.composer/cache"

install:
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar config --global github-oauth.github.com $GH_TOKEN
  - php -d memory_limit=-1 composer install --no-interaction

script:
  - php composer test
  - php composer phpmd

notifications:
  slack:
    secure: ftRvNV63xeXDtsziZo1+vqkGdFn6FjufnhCY5MyrhaFP3tgQoscxc2P4QH/LsabIqd9SgEGW6qW0jbC1x8rtEHiIVdhgtMMa9wCc6nuhYf61dPhvXIrwR/JvxTkIyzRGv8LgBtB/AQnY7Ana5NG2agjDroUPMdhFZ7EGnGmKx7guUioFuo1YRVgkp7RAxyA0NUUaguo/j9FJjuUUCc63gOUE+JSgn+IoGRli+9m7lDxWKOKne7bg3/1rqSMtcMSKelyfhmVrDVJyQMXdoFNPmYHTYopU82sVF8k+gFhgemAC/6eo0QaolnzQ6e85sDJ2WFlD+z5IE6waG4TrvUp0PXkV/EUP8Y5yDgXZlEZPhdb+l6pXaP5TQCVazq0JFRKHPdZ38Eax/62a7z5AB090VQ+PliSF647HnB7IMvMkStKq+Z2hM1oWfba4O6Ulmk/EN1fLWLC0qgQpgT20bsyn1uDAB0YM8E9HTXAy0v7ytnVBlTYYDcXdKk+nYj+WFDgYcJXzJzLHgcawIFdRUOuggI7MtkI4rY0+dt2eKsfDovA2XWLFPM189WpXIkjwnHlS4fgz44fWhZc3J2UyXmccidCM520qfs7EKUbxFypIFa1ffWzp0tITVdtbEoTbiKcCisTyolTgF1xPOxCdy0DGljWLGgudat4/ehJJNhnJOAo=
